-- CreateTable
CREATE TABLE "User" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "name" STRING NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Asset" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT8 NOT NULL,
    "title" STRING NOT NULL,
    "description" STRING NOT NULL,
    "private" BOOL NOT NULL,
    "type" STRING NOT NULL,
    "data" JSONB NOT NULL,

    CONSTRAINT "Asset_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "Asset" ADD CONSTRAINT "Asset_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
